version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: smartplaydb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  smartplay:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      MYSQLHOST: mysql
      MYSQLPORT: 3306
      MYSQLDATABASE: smartplaydb
      MYSQLUSER: root
      MYSQLPASSWORD: password


volumes:
  mysql_data:
