services:
  - type: web
    name: smartplay-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: MYSQLHOST
        fromDatabase:
          name: smartplaydb
          property: host
      - key: MYSQLPORT
        fromDatabase:
          name: smartplaydb
          property: port
      - key: MYSQLDATABASE
        fromDatabase:
          name: smartplaydb
          property: database
      - key: MYSQLUSER
        fromDatabase:
          name: smartplaydb
          property: user
      - key: MYSQLPASSWORD
        fromDatabase:
          name: smartplaydb
          property: password
      - key: SPRING_MAIL_PASSWORD
        value: unew wlkb qzmf ctwq

databases:
  - name: smartplaydb
    databaseName: smartplaydb
    user: admin
